Added information about community edition
tobspr-games/shapez-community-edition pull request #2
Opened 2022-11-12 15:11 UTC by DJ1TJOO

2022-11-13 04:06 UTC, EmeraldBlock requested changes
me picking apart the 2-line change

2022-11-13 04:06 UTC, EmeraldBlock commented on README.md
> +Shapez Community Edition is a community maintained version of shapez.
hyphenate "community-maintained"

2022-11-13 04:06 UTC, EmeraldBlock commented on README.md
> +# Shapez Community Edition
"shapez" is lowercase

2022-11-13 04:06 UTC, EmeraldBlock commented on README.md
> +Shapez Community Edition is a community maintained version of shapez.
perhaps mention the abbreviation "shapez CE"?

2022-11-13 04:06 UTC, EmeraldBlock commented on README.md
>  # shapez
just inserting a new section makes for a rough transition

2022-11-13 04:06 UTC, EmeraldBlock commented on README.md
> +
need more details!!!

2022-11-13 07:50 UTC, DJ1TJOO commented
> me picking apart the 2-line change

This was just more so there is something about it on the page. Else people get to the repo and don't know what's going on

2022-11-15 20:13 UTC, garretsimpson commented
Most of the existing readme should be deleted.

For now it should just be a header, a short description, a discord link, and a link back to the game.  Later it will need how to sections on building, contributing, bug reporting, suggestions, etc.

2023-11-18 22:13 UTC, EmeraldBlock approved these changes
rewrote README; bagel and dengr approved

2023-11-18 22:19 UTC, merged